server:
  port: 8081
spring:
  rabbitmq:
    host: localhost 
    port: 5672
    username: admin
    password: admin
    exchange:
      producer: ex.producer.message
    routing-key:
      producer: rk.producer.message
    deadletter:
      producer: dl.producer.message
